name: Benchmark PR

on:
  pull_request:
    branches: [main]
env:
  PYTHON_VERSION: "3.10"
  WORKING_DIR: ${{ github.workspace }}/src
  BENCHMARKS_OUTPUT: ${{ github.workspace }}/src/results

jobs:
  benchmark-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install asv virtualenv lf-asv-formatter

    - name: Create ASV machine config file
      run: asv machine --machine gh-runner --yes

    - name: Run Benchmarks - `PR HEAD` vs `main`
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        asv run --quick --interleave-rounds -a repeat=3 || true

    - name: BENCHMARK RESULTS
      run: |
        asv show HEAD

    - name: Upload Benchmark Results Folder
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: ${{ env.BENCHMARKS_OUTPUT }}
